# Cloud Build configuration for automatic deployments to Cloud Run
# This file is used by Cloud Build to build and deploy the API service

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/api:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/api:latest',
      '-t', 'gcr.io/$PROJECT_ID/api:$BRANCH_NAME',
      '--build-arg', 'COMMIT_SHA=$COMMIT_SHA',
      '--cache-from', 'gcr.io/$PROJECT_ID/api:latest',
      '.'
    ]

  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/api']

  # Step 3: Deploy to Cloud Run (production)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'api',
      '--image', 'gcr.io/$PROJECT_ID/api:$COMMIT_SHA',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 'COMMIT_SHA=$COMMIT_SHA,ENV=production',
      '--service-account', '${_SERVICE_ACCOUNT}',
      '--min-instances', '${_MIN_INSTANCES}',
      '--max-instances', '${_MAX_INSTANCES}',
      '--memory', '${_MEMORY}',
      '--cpu', '${_CPU}',
      '--timeout', '${_TIMEOUT}',
      '--concurrency', '${_CONCURRENCY}'
    ]

  # Step 4: Run smoke tests (optional)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE_URL=$(gcloud run services describe api --platform managed --region ${_REGION} --format 'value(status.url)')
        echo "Testing service at: $${SERVICE_URL}"
        curl -f "$${SERVICE_URL}/heartbeat" || exit 1
        echo "Smoke test passed!"

# Substitution variables with defaults
substitutions:
  _REGION: us-central1
  _SERVICE_ACCOUNT: api-service@${PROJECT_ID}.iam.gserviceaccount.com
  _MIN_INSTANCES: '1'
  _MAX_INSTANCES: '100'
  _MEMORY: '512Mi'
  _CPU: '1'
  _TIMEOUT: '60s'
  _CONCURRENCY: '80'

# Build configuration options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'
  substitutionOption: 'ALLOW_LOOSE'

# Build timeout (45 minutes)
timeout: '2700s'

# Tags for organizing builds
tags:
  - 'api'
  - 'production'
  - '$BRANCH_NAME'